require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DirectivosController do

  # This should return the minimal set of attributes required to create a valid
  # Directivo. As you add validations to Directivo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DirectivosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all directivos as @directivos" do
      directivo = Directivo.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:directivos)).to eq([directivo])
    end
  end

  describe "GET show" do
    it "assigns the requested directivo as @directivo" do
      directivo = Directivo.create! valid_attributes
      get :show, {:id => directivo.to_param}, valid_session
      expect(assigns(:directivo)).to eq(directivo)
    end
  end

  describe "GET new" do
    it "assigns a new directivo as @directivo" do
      get :new, {}, valid_session
      expect(assigns(:directivo)).to be_a_new(Directivo)
    end
  end

  describe "GET edit" do
    it "assigns the requested directivo as @directivo" do
      directivo = Directivo.create! valid_attributes
      get :edit, {:id => directivo.to_param}, valid_session
      expect(assigns(:directivo)).to eq(directivo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Directivo" do
        expect {
          post :create, {:directivo => valid_attributes}, valid_session
        }.to change(Directivo, :count).by(1)
      end

      it "assigns a newly created directivo as @directivo" do
        post :create, {:directivo => valid_attributes}, valid_session
        expect(assigns(:directivo)).to be_a(Directivo)
        expect(assigns(:directivo)).to be_persisted
      end

      it "redirects to the created directivo" do
        post :create, {:directivo => valid_attributes}, valid_session
        expect(response).to redirect_to(Directivo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved directivo as @directivo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Directivo.any_instance.stub(:save).and_return(false)
        post :create, {:directivo => { "nombre" => "invalid value" }}, valid_session
        expect(assigns(:directivo)).to be_a_new(Directivo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Directivo.any_instance.stub(:save).and_return(false)
        post :create, {:directivo => { "nombre" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested directivo" do
        directivo = Directivo.create! valid_attributes
        # Assuming there are no other directivos in the database, this
        # specifies that the Directivo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Directivo).to receive(:update).with({ "nombre" => "MyString" })
        put :update, {:id => directivo.to_param, :directivo => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested directivo as @directivo" do
        directivo = Directivo.create! valid_attributes
        put :update, {:id => directivo.to_param, :directivo => valid_attributes}, valid_session
        expect(assigns(:directivo)).to eq(directivo)
      end

      it "redirects to the directivo" do
        directivo = Directivo.create! valid_attributes
        put :update, {:id => directivo.to_param, :directivo => valid_attributes}, valid_session
        expect(response).to redirect_to(directivo)
      end
    end

    describe "with invalid params" do
      it "assigns the directivo as @directivo" do
        directivo = Directivo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Directivo.any_instance.stub(:save).and_return(false)
        put :update, {:id => directivo.to_param, :directivo => { "nombre" => "invalid value" }}, valid_session
        expect(assigns(:directivo)).to eq(directivo)
      end

      it "re-renders the 'edit' template" do
        directivo = Directivo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Directivo.any_instance.stub(:save).and_return(false)
        put :update, {:id => directivo.to_param, :directivo => { "nombre" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested directivo" do
      directivo = Directivo.create! valid_attributes
      expect {
        delete :destroy, {:id => directivo.to_param}, valid_session
      }.to change(Directivo, :count).by(-1)
    end

    it "redirects to the directivos list" do
      directivo = Directivo.create! valid_attributes
      delete :destroy, {:id => directivo.to_param}, valid_session
      expect(response).to redirect_to(directivos_url)
    end
  end

end
