require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FormatosController do

  # This should return the minimal set of attributes required to create a valid
  # Formato. As you add validations to Formato, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "pdf" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FormatosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all formatos as @formatos" do
      formato = Formato.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:formatos)).to eq([formato])
    end
  end

  describe "GET show" do
    it "assigns the requested formato as @formato" do
      formato = Formato.create! valid_attributes
      get :show, {:id => formato.to_param}, valid_session
      expect(assigns(:formato)).to eq(formato)
    end
  end

  describe "GET new" do
    it "assigns a new formato as @formato" do
      get :new, {}, valid_session
      expect(assigns(:formato)).to be_a_new(Formato)
    end
  end

  describe "GET edit" do
    it "assigns the requested formato as @formato" do
      formato = Formato.create! valid_attributes
      get :edit, {:id => formato.to_param}, valid_session
      expect(assigns(:formato)).to eq(formato)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Formato" do
        expect {
          post :create, {:formato => valid_attributes}, valid_session
        }.to change(Formato, :count).by(1)
      end

      it "assigns a newly created formato as @formato" do
        post :create, {:formato => valid_attributes}, valid_session
        expect(assigns(:formato)).to be_a(Formato)
        expect(assigns(:formato)).to be_persisted
      end

      it "redirects to the created formato" do
        post :create, {:formato => valid_attributes}, valid_session
        expect(response).to redirect_to(Formato.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved formato as @formato" do
        # Trigger the behavior that occurs when invalid params are submitted
        Formato.any_instance.stub(:save).and_return(false)
        post :create, {:formato => { "pdf" => "invalid value" }}, valid_session
        expect(assigns(:formato)).to be_a_new(Formato)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Formato.any_instance.stub(:save).and_return(false)
        post :create, {:formato => { "pdf" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested formato" do
        formato = Formato.create! valid_attributes
        # Assuming there are no other formatos in the database, this
        # specifies that the Formato created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Formato).to receive(:update).with({ "pdf" => "MyString" })
        put :update, {:id => formato.to_param, :formato => { "pdf" => "MyString" }}, valid_session
      end

      it "assigns the requested formato as @formato" do
        formato = Formato.create! valid_attributes
        put :update, {:id => formato.to_param, :formato => valid_attributes}, valid_session
        expect(assigns(:formato)).to eq(formato)
      end

      it "redirects to the formato" do
        formato = Formato.create! valid_attributes
        put :update, {:id => formato.to_param, :formato => valid_attributes}, valid_session
        expect(response).to redirect_to(formato)
      end
    end

    describe "with invalid params" do
      it "assigns the formato as @formato" do
        formato = Formato.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Formato.any_instance.stub(:save).and_return(false)
        put :update, {:id => formato.to_param, :formato => { "pdf" => "invalid value" }}, valid_session
        expect(assigns(:formato)).to eq(formato)
      end

      it "re-renders the 'edit' template" do
        formato = Formato.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Formato.any_instance.stub(:save).and_return(false)
        put :update, {:id => formato.to_param, :formato => { "pdf" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested formato" do
      formato = Formato.create! valid_attributes
      expect {
        delete :destroy, {:id => formato.to_param}, valid_session
      }.to change(Formato, :count).by(-1)
    end

    it "redirects to the formatos list" do
      formato = Formato.create! valid_attributes
      delete :destroy, {:id => formato.to_param}, valid_session
      expect(response).to redirect_to(formatos_url)
    end
  end

end
