require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TemasNoRegistradosController do

  # This should return the minimal set of attributes required to create a valid
  # TemaNoRegistrado. As you add validations to TemaNoRegistrado, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "titulo" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TemasNoRegistradosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all temas_no_registrados as @temas_no_registrados" do
      tema_no_registrado = TemaNoRegistrado.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:temas_no_registrados)).to eq([tema_no_registrado])
    end
  end

  describe "GET show" do
    it "assigns the requested tema_no_registrado as @tema_no_registrado" do
      tema_no_registrado = TemaNoRegistrado.create! valid_attributes
      get :show, {:id => tema_no_registrado.to_param}, valid_session
      expect(assigns(:tema_no_registrado)).to eq(tema_no_registrado)
    end
  end

  describe "GET new" do
    it "assigns a new tema_no_registrado as @tema_no_registrado" do
      get :new, {}, valid_session
      expect(assigns(:tema_no_registrado)).to be_a_new(TemaNoRegistrado)
    end
  end

  describe "GET edit" do
    it "assigns the requested tema_no_registrado as @tema_no_registrado" do
      tema_no_registrado = TemaNoRegistrado.create! valid_attributes
      get :edit, {:id => tema_no_registrado.to_param}, valid_session
      expect(assigns(:tema_no_registrado)).to eq(tema_no_registrado)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TemaNoRegistrado" do
        expect {
          post :create, {:tema_no_registrado => valid_attributes}, valid_session
        }.to change(TemaNoRegistrado, :count).by(1)
      end

      it "assigns a newly created tema_no_registrado as @tema_no_registrado" do
        post :create, {:tema_no_registrado => valid_attributes}, valid_session
        expect(assigns(:tema_no_registrado)).to be_a(TemaNoRegistrado)
        expect(assigns(:tema_no_registrado)).to be_persisted
      end

      it "redirects to the created tema_no_registrado" do
        post :create, {:tema_no_registrado => valid_attributes}, valid_session
        expect(response).to redirect_to(TemaNoRegistrado.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tema_no_registrado as @tema_no_registrado" do
        # Trigger the behavior that occurs when invalid params are submitted
        TemaNoRegistrado.any_instance.stub(:save).and_return(false)
        post :create, {:tema_no_registrado => { "titulo" => "invalid value" }}, valid_session
        expect(assigns(:tema_no_registrado)).to be_a_new(TemaNoRegistrado)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TemaNoRegistrado.any_instance.stub(:save).and_return(false)
        post :create, {:tema_no_registrado => { "titulo" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tema_no_registrado" do
        tema_no_registrado = TemaNoRegistrado.create! valid_attributes
        # Assuming there are no other temas_no_registrados in the database, this
        # specifies that the TemaNoRegistrado created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(TemaNoRegistrado).to receive(:update).with({ "titulo" => "MyString" })
        put :update, {:id => tema_no_registrado.to_param, :tema_no_registrado => { "titulo" => "MyString" }}, valid_session
      end

      it "assigns the requested tema_no_registrado as @tema_no_registrado" do
        tema_no_registrado = TemaNoRegistrado.create! valid_attributes
        put :update, {:id => tema_no_registrado.to_param, :tema_no_registrado => valid_attributes}, valid_session
        expect(assigns(:tema_no_registrado)).to eq(tema_no_registrado)
      end

      it "redirects to the tema_no_registrado" do
        tema_no_registrado = TemaNoRegistrado.create! valid_attributes
        put :update, {:id => tema_no_registrado.to_param, :tema_no_registrado => valid_attributes}, valid_session
        expect(response).to redirect_to(tema_no_registrado)
      end
    end

    describe "with invalid params" do
      it "assigns the tema_no_registrado as @tema_no_registrado" do
        tema_no_registrado = TemaNoRegistrado.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TemaNoRegistrado.any_instance.stub(:save).and_return(false)
        put :update, {:id => tema_no_registrado.to_param, :tema_no_registrado => { "titulo" => "invalid value" }}, valid_session
        expect(assigns(:tema_no_registrado)).to eq(tema_no_registrado)
      end

      it "re-renders the 'edit' template" do
        tema_no_registrado = TemaNoRegistrado.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TemaNoRegistrado.any_instance.stub(:save).and_return(false)
        put :update, {:id => tema_no_registrado.to_param, :tema_no_registrado => { "titulo" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tema_no_registrado" do
      tema_no_registrado = TemaNoRegistrado.create! valid_attributes
      expect {
        delete :destroy, {:id => tema_no_registrado.to_param}, valid_session
      }.to change(TemaNoRegistrado, :count).by(-1)
    end

    it "redirects to the temas_no_registrados list" do
      tema_no_registrado = TemaNoRegistrado.create! valid_attributes
      delete :destroy, {:id => tema_no_registrado.to_param}, valid_session
      expect(response).to redirect_to(temas_no_registrados_url)
    end
  end

end
